# Generated by Django 5.0.4 on 2024-05-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_chatmessage_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default_profile_pic.jpg', upload_to='profile_pics'),
        ),
    ]
